//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleDeCarga.Models
{
    using Microsoft.AspNet.Identity.EntityFramework;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Veiculo: ModificationControlledModel
    {
        public Veiculo()
        {
            //this.HistoricoCarga = new HashSet<HistoricoCarga>();
        }
    
        public int Id { get; set; }
        public string Placa { get; set; }

        [DisplayName("Tipo")]
        public Nullable<int> TipoVeiculoId { get; set; }
        
    
        //public virtual ICollection<HistoricoCarga> HistoricoCarga { get; set; }
        public virtual TipoVeiculo TipoVeiculo { get; set; }
        
       


    }
}
